for num_genes = [100, 500, 800, 1000, 3000]
    data_loc = '../../data/brca/';
    save_loc = '/home/vaishnavis/code/gcca_fusion_results/'; %'../../results/brca';
    L_graph = table2array(readtable(strcat(data_loc, ...
        '/ordered_graph_laplacian_', num2str(num_genes), '.csv')));

    L_graph = L_graph / norm (L_graph);
    num_img_features = 213;
 
    %% Sparse CCA (from Group CCA package)
   rng(42)

   sparse_cca_params = struct("lambda1", 0.1:sqrt(num_genes)/10:sqrt(num_genes), ...
                           "lambda2", 0.1:sqrt(num_img_features)/10:sqrt(num_img_features));

   add_paths = ['/methods/group_scca/'];
   settings = struct('add_path', add_paths, ...
           'need_laplacian', false, ...
           'params', sparse_cca_params, ...
           'function_call', @sparse_cca, ...
           'save_name', 'sparse_', ...
           'save_loc', save_loc, ...
           'itr', 0);

   run_brca(num_genes, data_loc, settings, [])

   %% GN-SCCA

   rng(42)

   params_struct_1 = struct("alpha1", [10^(-1), 1, 10, 100, 1000], ...
       "alpha2", [10^(-1), 1, 10, 100, 1000], ...
       "lambda1", [10^(-1), 1, 10, 100, 1000], ... % 0.2:0.2:0.6 ... %1:2:10, ...
       "lambda2", [10^(-1), 1, 10, 100, 1000], ... % 0.2:1:2:10, ...
       "beta1", [1, 10, 100], ...
       "beta2", [1, 10, 100]);

   add_paths = ['/methods/gn_scca/', '/methods/data_processing/'];
   settings = struct('add_path', add_paths, ...
       'need_laplacian', false, ...
       'params', params_struct_1, ...
       'function_call', @gn_scca, ...
       'save_loc', save_loc, ...
       'save_name', 'gn_orig_', ...
       'run_mode', "orig", ...
       'itr', 0);

    run_brca(num_genes, data_loc, settings, [])
                                  
  %% GN-SCCA-PPIN

   rng(42)

   params_struct_1 = struct("alpha1", [10^(-1), 1, 10, 100, 1000], ...
       "alpha2", [10^(-1), 1, 10, 100, 1000], ...
       "lambda1", [10^(-1), 1, 10, 100, 1000], ... % 0.2:0.2:0.6 ... %1:2:10, ...
       "lambda2", [10^(-1), 1, 10, 100, 1000], ... % 0.2:1:2:10, ...
       "beta1", [1, 10, 100], ...
       "beta2", [1, 10, 100]);

   add_paths = ['/methods/gn_scca/', '/methods/data_processing/'];
   settings = struct('add_path', add_paths, ...
       'need_laplacian', true, ...
       'params', params_struct_1, ...
       'function_call', @gn_scca, ...
       'save_loc', save_loc, ...
       'save_name', 'gn_prior_', ...
       'run_mode', "laplacian", ...
       'itr', 0);

    run_brca(num_genes, data_loc, settings, L_graph)
                                  
  
    %% GCCA
    
    params_struct_3 = struct("mu1",  [0.01, 0.1, 1], ...
            "mu2",  [0.01, 0.1, 1], ...
            "alpha1",  [0.01, 0.1, 1], ...
            "alpha2",  [0.01, 0.1, 1], ...
            "gamma1",  [0.01, 0.1, 1], ...
            "gamma2", [0.01, 0.1, 1]);
        
    add_paths = ['/methods/graph_cca_proximal/', '/methods/data_processing/'];
    settings = struct('add_path', add_paths, ...
        'need_laplacian', false, ...    
        'params', params_struct_3, ...
        'function_call', @graph_cca_proximal_gn, ...
        'save_name', 'graph_cca_proximal_', ...
        'save_loc', save_loc, ...
        'run_mode', "proximal", ...
        'itr', 0);
    
     run_brca(num_genes, data_loc, settings, [])
     
    %% GCCA-PPIN

    params_struct_3 = struct("mu1",  [0.01, 0.1, 1], ...
            "mu2",  [0.01, 0.1, 1], ...
            "alpha1",  [0.01, 0.1, 1], ...
            "alpha2",  [0.01, 0.1, 1], ...
            "gamma1",  [0.01, 0.1, 1], ...
            "gamma2", [0.01, 0.1, 1]);
        
    add_paths = ['/methods/graph_cca_proximal/', '/methods/data_processing/'];
    settings = struct('add_path', add_paths, ...
        'need_laplacian', true, ...
        'params', params_struct_3, ...
        'function_call', @graph_cca_proximal, ...
        'save_name', 'graph_cca_proximal_prior_', ...
        'save_loc', save_loc, ...
        'run_mode', "proximal_prior", ...
        'itr', 0);
    
     run_brca(num_genes, data_loc, settings, L_graph)
end
