clear all;
close all;

addpath('../01_methods/cca')
addpath('../01_methods/group_scca')
addpath('../01_methods/gn_scca')
addpath('../01_methods/data_preprocessing')
addpath('../01_methods/deflation')
data_loc = 'data/splits_journal/';
save_loc = 'results/';

rng(0)

for num_genes = [1000]
    tic
    
    suffix = '_log_histogram';
    num_img_features = 1075;
    d = 50;

    cca_params = struct("dim", d);

    sparse_cca_params = struct("lambda1", 0.1:sqrt(num_genes)/10:sqrt(num_genes), ...
                            "lambda2", 0.1:sqrt(num_img_features)/10:sqrt(num_img_features), ...
                             "dim", d);

    gnscca_params = struct("alpha1", [10^(-1), 1], ...
                "alpha2", [10^(-1), 1], ...
                "lambda1", [10^(-1), 1], ... 
                "lambda2", [10^(-1), 1], ... 
                "beta1", [1, 10], ...
                "beta2", [1, 10], ...
                "dim", d);
     
    gcca_params = struct("mu1",  [0.01, 0.1], ...
                "mu2",  [0.01, 0.1], ...
                "alpha1",  [0.1, 1], ...
                "alpha2",  [0.1, 1], ...
                "gamma1",  [0.01, 0.1], ...
                "gamma2", [0.01, 0.1], ...
                "dim", d);
    
    %%% SCCA-HD
    add_paths = ['/methods/group_scca/'];
    settings = struct('add_path', add_paths, ...
            'need_laplacian', false, ...
            'params', sparse_cca_params, ...
            'function_call', @sparse_cca_hd, ...
            'save_name', 'sparse_hd_', ...
            'save_loc', save_loc, ...
            'itr', 0);
    run_brca_multiple(num_genes, data_loc, settings, [], suffix)
        
    %%% GNSCCA-HD
%     add_paths = ['/methods/gn_scca/', '/methods/data_processing/'];
%     settings = struct('add_path', add_paths, ...
%             'need_laplacian', false, ...
%             'params', gnscca_params, ...
%             'function_call', @gn_scca_hd, ...
%             'save_name', 'gnscca_hd_', ...
%             'run_mode', "orig", ...
%             'save_loc', save_loc, ...
%             'itr', 0);
%     run_brca_multiple(num_genes, data_loc, settings, [], suffix)
        
    %%% SCCA-PD 
    add_paths = ['/methods/group_scca/'];
    settings = struct('add_path', add_paths, ...
            'need_laplacian', false, ...
            'params', sparse_cca_params, ...
            'function_call', @sparse_cca_pd, ...
            'save_name', 'sparse_pd_', ...
            'save_loc', save_loc, ...
            'itr', 0);
    run_brca_multiple(num_genes, data_loc, settings, [], suffix)
    
    %%% GNSCCA-PD 
%     add_paths = ['/methods/gn_scca/', '/methods/data_processing/'];
%     settings = struct('add_path', add_paths, ...
%             'need_laplacian', false, ...
%             'params', gnscca_params, ...
%             'function_call', @gn_scca_pd, ...
%             'save_name', 'gnscca_pd_', ...
%             'save_loc', save_loc, ...
%             'run_mode', "orig", ...
%             'itr', 0);
%     run_brca_multiple(num_genes, data_loc, settings, [], suffix)
    
    %%% SCCA-OPD 
    add_paths = ['/methods/group_scca/'];
    settings = struct('add_path', add_paths, ...
            'need_laplacian', false, ...
            'params', sparse_cca_params, ...
            'function_call', @sparse_cca_opd, ...
            'save_name', 'sparse_opd_', ...
            'save_loc', save_loc, ...
            'itr', 0);

    run_brca_multiple(num_genes, data_loc, settings, [], suffix)

    %%% GNSCCA-OPD 
%     add_paths = ['/methods/gn_scca/', '/methods/data_processing/'];
%     settings = struct('add_path', add_paths, ...
%             'need_laplacian', false, ...
%             'params', gnscca_params, ...
%             'function_call', @gn_scca_opd, ...
%             'save_name', 'gnscca_opd_', ...
%             'save_loc', save_loc, ...
%             'run_mode', "orig", ...
%             'itr', 0);
%     run_brca_multiple(num_genes, data_loc, settings, [], suffix)
    
    toc
    
end
